---
- name: Update Ubuntu Server
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes

    - name: Detecting systems that need reboot
      ansible.builtin.debug:
      with_file: "/var/run/reboot-required"
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true