---
- name: Update Ubuntu Server
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: yes

- name: Update the Unifi Control software
  hosts: unifi.cerberusnet.net
  tasks:
    - name: Task 1
      apt:
        name: unifi
        state: latest